/**
 * Created by zhenyu 2018/06/25.
 */
define([], function () {
    var defaultLang = 'zh-CN';
    var lang = navigator.language || defaultLang;
    var query=window.navigator.userAgent.split(" ");
    for(var i=0;i<query.length;i++){
        if(query[i].indexOf('youZoneLanguage=')>-1){
            lang=query[i].split('=')[1];
        }
    }
    if(lang.toLowerCase()=='tw'){
        lang='zh-CN';
    }
    lang = /^zh/.test(lang) ? 'zh-CN' : /^en/.test(lang) ? 'en' : /^es/.test(lang) ? 'es' : lang;
    var languageJson;
    if(lang==='zh-CN'){
        languageJson={
            'ApprovalHeader':'审批',
            'Manage':'管理',
            'done':'完成',
            'appName':"由 <span style='color: #29b6f6'>友空间</span> 提供支持",
            'tasksToProcess':'待审批',
            'tasksCopiedToMe':'抄送的',
            'tasksProcessed':'已审批',
            'tasksCreatedMyself':'我发起的',
            'allStates':'全部状态',
            'overdue':'逾期',
            'addApproving':'加签中',
            'normal':'正常',
            'receiveTime':'接收时间',
            'submitTime':'提交时间',
            'pickFormCategory':'全部分类',
            'submit':'提交',
            'saveDraft':'暂存',
            'required':'不能为空',
            'divisorNotBeZero':'除数不能为零',
            'noMoreThan':'不能大于',
            'noLessThan':'不能小于',
            'formDetail':'表单（详情）',
            'processDetail':'流程（详情）',
            'documentDetail':'公文正文',
            'agree':'同意',
            'reject':'驳回',
            'prependTask':'前加签',
            'appendTask':'后加签',
            'withdrawSubmission':'撤回提交',
            'withdrawApproval':'撤回',
            'convertToEsnTask':'转任务',
            'jumpTo':'Redirect',
            'reassign':'改派',
            'submitter':'提交人',
            'noAttachment':'暂无附件',
            'noContent':'暂无内容',
            'copyTo':'添加抄送人',

            //首页输入框 下拉加载等
            'cancel':'取消',
            'confirm':'确定',
            'continue':'继续',
            'clear':'清除',
            'searchTitle':'搜索标题',
            'pullToRefresh':'下拉刷新',
            'releaseToUpdate':'释放更新',
            'loading':'正在加载',
            'showDone':'已显示所有数据',
            'detailWrapName':'明细子表',
            'shareYonYouForm':'友空间表单',
            'personnelAddTitle':'人员',
            'nameIsNull':'未命名',
            'unknown':'未知',
            'autoCode':'自动编号',
            'reAgain':'重新获取',
            'dateStart':'(开始)',
            'dateEnd':'(结束)',
            //组件标题
            'componentTitle':{
                'department':'部门',
                'employee':'用户',
                'selectTitle':'选项',
                'dateTitle':'日期',
                'emailTitle':'邮箱',
                'linkTitle':'超链接',
                'phoneTitle':'手机号码',
                'passwordTitle':'密码',
                'textTitle':'文本',
                'textareaTitle':'多行文本',
                'moneyTitle':'金额',
                'numberTitle':'数值',
                'percentTitle':'百分比',
                'referFieldTitle':'关联参照',
                'relevance':'关联',
                'selected':'已选择 ',
                'selectedZero':'已选择 0 ',
                'default':'默认',
                'Settings':'自定义',
                'SelectInitiatingDepartment':'请选择发起部门',
                'partTime':'（兼职）',
                'help':'帮助',
                'copyuser':'抄送人:'

            },
            'dealPage':{
                'selectProcessor':'请选择处理人',
                'selectStepProcessor':'请选择指派环节处理人',
                'approvalOpinion':'审批意见',
                'remind':'催办',
                'turnOver':'转交给',
                'stepUnDefine':'环节名称未定义（审批人：',
                'unspecified':'未指定',
                'rejectToTerminal':'驳回到终止审批',
                'rejectToMaker':'驳回到制单人',
                'informInitiator':'终止当前审批流并通知发起人',
                'stepUnnamed':'环节名称未定义',
                'assign':'加签',
                'rejectComments':"不同意 ",
                'unSignBeforeApproval':'未进行签名审批，请签名后再提交！',
                'commonPhrase':'保存为常用语',
                'addCommonPhrase':'添加常用语',
                'noCommonPhrase':'暂无常用语，请设置或添加常用语！',
                'adding':'添加中',
                'enterPhrase':'请输入您想添加的常用语',
                'submitAfterSign':'点击完成前，请先完成签名！',
                'uploadSignImage':'签名图片上传中...',
                'end':'结束',
                'assignParticipants':'加签人',
                'assignStyle':'加签方式',
                'raceToApproval':'抢占',
                'togetherApproval':'会签',
                'gateway':'网关',
                'circulatePerson':'传阅人',
            },
            'referenceListPage':{
                'taskname':'任务名称',
                'projectname':'项目名称',
                'running':'审批中',
                'done':'已完成',
                'delayed':'已延期',
                'archived':'已归档',
                'status':'状态：',
                'deadline':'截止日期：',
                'relevantProject':'关联项目：',
                'manager':'负责人：',
                'post':'岗位：',
                'duty':'职务：',
                'cancel':'已取消',
                'notStart':'未开始',
            },
            'cloudSign':{
                'place':"请在下面指定区域签名",
                'undo':"后退",
                'redo':"前进",
                'reset':"清空",
                'choseColor':"颜色",
                'back':"返回",
                'save':"完成",
            },
            'placeholder':{
                'agreeComments':'请输入同意理由（非必填, 2000字以内）',
                'rejectComments':'请输入拒绝理由（非必填, 2000字以内）',
                'remindComments':'请输入催办内容 （2000字以内）',
                'remindApproval':'催您审批“',
                'approvalImmediately':'”，赶快去处理吧。',
            },
            //填表单 审批操作按钮等
            "formAction":{
                'submit':'提交',
                'tempsave':'暂存',
                "copyTo":'添加抄送人',
                "addApprover":'添加审批人',
                "deleteMember":'点击头像可删除',
                "approveSettingByManager":'审批人已由管理员内置',
                "loadApproveError":"审批人获取失败,点击重新加载",
                "addDetailRow":'增加明细',
                "pleaseSelect":'请选择 ',
                'agree':'同意',
                'reject':'驳回',
                'copy':'抄送',
                'assignBefore':'前加签',
                'assignAfter':'后加签',
                'edit':'编辑',
                'delete':'删除',
                'attaContributor':'贡献者：',
                'resubmit':'重新提交',
                'copyForm':'复制表单',
                'deleteForm':'删除表单',
                'withdrawSubmission':'撤回提交',
                'reassign':'改派',
                'jumpTo':'跳转',
                'convertToEsnTask':'转任务',
                'withdrawApproval':'撤回',
                'cloudSign':'云签名',
                'historySign':'历史签名',
                'commonPhrase':'常用语',
                'add':'添加',
                'new':'新增',
                'continueSubmission':'继续提交',
                'circulate':'传阅',
                'read':'阅办',
                'close':'关闭',
                'batchOperation':'批量审批',
                'batchConsent':'批量同意',
                'selectAll':'全选',
                'processMap':'流程图',
                'iformBrowserUrl':'表单全貌'
            },
            "numberText":{
                'max':'最大值',
                'min':'最小值',
                'sum':'求和',
                'average':'平均',
                'uppercase':'大写'
            },
            'formTips':{
                "formDetail":'详情',
                "processDetail":'流程',
                'documentDetail':'公文正文',
                "attachment":'附件',
                "attachmentProcess":'流程附件',
                'uploadFile':'上传附件',
                'PleaseUploadFile':'请上传附件',
                "addApproverRepeat":'不能添加重复的审批人',
                "deleteDataTableTips":'你确定要删除该明细吗？',
                "tempsaving":'正在暂存...',
                "submitting":'正在提交...',
                "pleaseSelectApprove":'请选择审批人',
                "processErrorManagerFix":'本单据审批流程错误!请联系管理员配置修改',
                "branchHasNoProcessor":'分支没有选择处理人，请选择！',
                'tempsaveSuccess':'已暂存成功',
                'submitSuccess':'已提交成功',
                'operationFailure':'操作失败!请稍后再试',
                'onLoading':'加载中...',
                'previewQRcode':'预览失败,在预览期间请勿关闭二维码,请重试!',
                'formatWrongTips':'格式不对',
                'formatErrorTips':'格式错误',
                'identifyCodePhone':'请输入手机号码！',
                "noMoreThan":'必须小于',
                "noLessThan":'必须大于',
                "divisorNotBeZero":'除数不能为零',
                "required":'为必填项',
                "validText":'请输入有效text',
                "textLimit":'请控制在200个字符以内',
                "textAreaLimit":'请控制在2000个字符以内',
                "phoneFormatWrong":'手机号格式不对!',
                "endDataMoreStartDate":'结束日期必须大于开始日期，请重新选择!',
                "startDataLessEndDate":'开始日期必须小于结束日期，请重新选择!',
                "linkFormatTips":'请输入正确的网址格式!',
                'moneyLengthLimitTips':'目前只支持16位字符',
                'approvalCommentsTips':'系统自动填入审批意见',
                'optionOtherSelectPlaceholder':'请输入其他内容',
                'noAttachment':'暂无附件',
                'noContent':'暂无内容',
                'confirmWithdraw':'确定要撤回正在进行的审批吗?',
                'approvalWithDrawing':'审批撤回中...',
                'confirmDeleteForm':'确定删除当前草稿单据吗?',
                'reassignPre':'确定要将审批单改派给',
                'reassignLast':'进行审批吗?',
                'reassignSuccess':'改派成功',
                'copyToSuccess':'抄送成功',
                'copyFormSuccess':'复制表单成功，正在跳转！',
                'serverRequestError':'服务请求失败',
                'confirmWithdrawApplication':'确定要撤销该申请吗?',
                'confirmWithdrawApproval':'确定要撤销该审批吗?',
                'withdrawnSuccess':'撤回成功',
                'uploadedSuccess':' 上传成功 ',
                'uploadedFailed':' 上传失败 ',
                'iconMissing':'丢失',
                'commentsMessage':'意见：',
                'finishJumpTo':'跳转完成',
                'finishSuccess':'跳转成功',
                'finishApprove':'跳转',
                'prependTaskRecalled':'前加签被撤回',
                'appendTaskRecalled':'后加签被撤回',
                'reassignRecalled':'改派被撤回',
                'jumpedWithNoParticipant':'找不到执行人跳过',
                'processedByOthers':'任务已被他人处理',
                'talkWithOtherPre':'确定要和',
                'talkWithOtherAft':'聊天？',
                'chartWaiting':'请稍后...',
                'formEnable':'启用中...',
                'formUnEnable':'停用中...',
                'sureToDisabledForm':'你确定要停用此表单吗?',
                'authorization':'授权中...',
                'successfullyApproved':'审批成功',
                'successfullyReject':'驳回成功',
                'assignParticipants':'请选择加签人',
                'assignTypes':'请选择加签方式',
                'assignFail':'加签失败',
                'assignSuccess':'加签成功',
                'designateFail':'指派失败',
                'failToComment':'评论失败',
                'selectRejectStep':'请选择驳回环节',
                'selectJumpStep':'请选择跳转环节',
                'noJumpStep':'跳转环节为空',
                'assignInformationEmpty':'指派信息中参与者不能为空',
                'branchNoProcessor':'分支没有选择处理人，请选择！',
                'canNotAssign':'任务不支持指派',
                'qrCodeError':'二维码已失效,<br/>无法参与相关活动',
                'thanksPage':'感谢您的填写!',
                'delete':'删除中...',
                'pleaseEnter':'请输入',
                'remindSuccess':'催办成功',
                'Processing':'处理中...',
                'enterRemindingContent':'请输入催办内容',
                'structureError':'模版结构错误！请联系管理员',
                'isNotANumber':'不是数值类型，请修改或者重新输入',
                'rejectTaskOnlyCompleted':"设置了'驳回环节直接审批'的驳回任务只能进行完成操作！",
                'notLaterThan':'不能晚于',
                'notEarlyThan':'不能早于',
                'deleteSuccess':'删除成功',
                'deleteFail':'删除失败，请稍后重试',
                'makeSureDeleteFile':'确定要删除该附件吗?',
                'confirmCC':'确定抄送给',
                'maxStringTips':'目前只支持16位字符!',
                'stars':' 星 ',
                'batchApprovalMore':'批量审批最多只支持选择20条待办，超过20条时只按顺序处理前20条！是否进行批量审批？',
                'selectApproveItem':'请选择审批表单！',
                'makesureToBatchApproval':'个待办，是否进行批量审批？',
                'batchSuccess':'成功',
                'batchFail':', 失败',
            },
            'time':{
                'year':' 年',
                'month':' 月',
                'day':' 日',
                'hour':' 小时',
                'min':' 分',
                'sec':' 秒',
                'today':' 今天',
                'yesterday':' 昨天',
                'thisWeek':' 本周',
                'lastWeek':' 上周',
                'thisMonth':'本月',
                'more':'更多',
                'receiveDate':'接收时间',
                'finishDate':'完成时间',
                'sendDate':'提交时间',
            },
            'status':{
                'all':'全部状态',
                'over':'逾期',
                'normal':'正常',
                'finish':'已完成',
                'going':'审批中',
                'stop':'已终止',
                'inApproval':'审批中',
                'draft':'草稿',
                'rejectDraft':'驳回草稿',
                'submitted':'已提交',
                'rejected':'驳回制单',
                'rejectedHung':'任务挂起(驳回制单人)',
                'overdueTerminated':'超期终止',
                'overTime':'超期',
                'warning':'预警',
                'SubmitApplication':'提交了申请',
                'billMaking':'制单',
                'suspendApplication':'中止申请'
            },
            'formTypes':{
                'all':'全部类型'
            },
            'selectAttachment':{
                'photo':'拍照',
                'video':'视频',
                'pic':'图库',
                'files':'文件',
            },
            'previewExtra':{
                'name':'附件.',
                'previewChoose':'附件操作选择',
                'preview':'预览',
                'downLoad':'下载',
                'downLoading':'下载中...',
            },
            'datePicker':{
                'year':' 年',
                'month':' 月',
                'day':' 日',
                'hour':' 时',
                'min':' 分',
                'sec':' 秒',
            },
            'dateCalculate':{
                'day':' (天)',
                'hour':' (时)',
                'min':' (分)',
                'sec':' (秒)',
            },
            'iconUrl':{
                'refuse':'./imgs/refuse.png',
                'agreee':'./imgs/agree.png',
            }
        };
    }else{
        languageJson={
            'ApprovalHeader':' Approval ',
            'Manage':' Manage ',
            'done':' Done ',
            'appName':"Provided by <span style='color: #29b6f6'> YouZone</span>",
            'tasksToProcess':' Pending ',
            'tasksCopiedToMe':' CC ',
            'tasksProcessed':' Approved ',
            'tasksCreatedMyself':' I Initiated ',
            'allStates':' All Status ',
            'overdue':' Overdue ',
            'addApproving':' Add Approving ',
            'normal':' Normal ',
            'receiveTime':' Receive Date ',
            'submitTime':' Send Date ',
            'pickFormCategory':' Category ',
            'submit':' Submit ',
            'saveDraft':' Save as Draft ',
            'required':' Required ',
            'divisorNotBeZero':' Cannot Be Zero ',
            'noMoreThan':' No More Than ',
            'noLessThan':' No Less Than ',
            'formDetail':' Form ',
            'processDetail':' Process ',
            'agree':' Consent ',
            'reject':' Reject ',
            'prependTask':' Add Approver Ahead ',
            'appendTask':' Add Approver Behind ',
            'withdrawSubmission':' Withdraw Submission ',
            'withdrawApproval':' Withdraw Approval ',
            'convertToEsnTask':' Convert as Task ',
            'jumpTo':' Redirect ',
            'reassign':' Reassign ',
            'submitter':' Submitter ',
            'noAttachment':' No Attachment ',
            'noContent':' No Content ',
            'copyTo':' Add CC ',

            //首页输入框 下拉加载等
            'cancel':' Cancel ',
            'confirm':' Confirm ',
            'continue':' Continue ',
            'clear':' Clear ',
            'searchTitle':' Title Searching ',
            'pullToRefresh':' Pull to Refresh ',
            'releaseToUpdate':' Release to Update ',
            'loading':' Loading ',
            'showDone':' All Data Displayed ',
            'detailWrapName':' Detail Sub-table ',
            'shareYonYouForm':' YouZone Form ',
            'personnelAddTitle':' Personnel ',
            'nameIsNull':' unnamed ',
            'unknown':' The unknown ',
            'autoCode':' Autonumber ',
            'reAgain':' Get it again ',
            'dateStart':' (Start) ',
            'dateEnd':' (End) ',
            'componentTitle':{
                'department':' Department ',
                'employee':' User ',
                'selectTitle':' Options ',
                'dateTitle':' Date ',
                'emailTitle':' Email ',
                'linkTitle':' Hyperlinks ',
                'phoneTitle':' Phone Number ',
                'passwordTitle':' Password ',
                'textTitle':' Text ',
                'textareaTitle':' Textarea ',
                'moneyTitle':' Money ',
                'numberTitle':' Number ',
                'percentTitle':' Percent ',
                'referFieldTitle':' ReferField ',
                'relevance':' Relevance',
                'selected':' Selected ',
                'selectedZero':' Selected 0 ',
                'default':'Default',
                'Settings':'Custom',
                'SelectInitiatingDepartment':'Process Initiator',
                'partTime':' (part-time) ',
                'help':' Help ',
                'copyuser':' CC：'
            },
            'dealPage':{
                'selectProcessor':' Please select processor ',
                'selectStepProcessor':' Please select step processor ',
                'approvalOpinion':' Approval comments ',
                'remind':' Remind ',
                'turnOver':' Transmit To ',
                'stepUnDefine':' Step name not set (Approver: ',
                'unspecified':' Unspecified ',
                'rejectToTerminal':' Terminate Process ',
                'rejectToMaker':' Form Creator ',
                'informInitiator':' Cease current approval process and inform initiator ',
                'stepUnnamed':' Step unnamed ',
                'assign':' Add Approver ',
                'rejectComments':" Don't agree ",
                'unSignBeforeApproval':' No signing approval. Please resubmit after signing! ',
                'commonPhrase':' Save as Common Phrase ',
                'addCommonPhrase':' Add Common Phrase ',
                'noCommonPhrase':' You do not have a common phrase yet, please set or add one ',
                'adding':'Adding...',
                'enterPhrase':'Please enter the phrase you want to add ',
                'submitAfterSign':'Please complete your signature before save ',
                'uploadSignImage':'The image of signing is uploading... ',
                'end':' End ',
                'assignParticipants':'Add Process Approver',
                'assignStyle':'Add Process Method',
                'raceToApproval':'Seize(Finish after any of the approvers process the task)',
                'togetherApproval':'Countersign(Not finish until all approvers process the task）',
                'gateway':' Gateway ',
                'circulatePerson':' circulator ',
            },
            'referenceListPage':{
                'taskname':' Task Name：',
                'projectname':' Project Name：',
                'running':' In Progress',
                'done':' Completed',
                'delayed':' Delayed',
                'archived':' Archived',
                'status':' Status：',
                'deadline':' Deadline：',
                'relevantProject':' Relevant Project：',
                'manager':' Manager：',
                'post':' Post：',
                'duty':' Duty：',
                'cancel':' Cancelled ',
                'notStart':' Not Started ',
            },
            'cloudSign':{
                'place':" Please sign in the specified area below ",
                'undo':" Undo ",
                'redo':" Redo ",
                'reset':" Reset ",
                'choseColor':" Color ",
                'back':" Back ",
                'save':" Save ",
            },
            'placeholder':{
                'agreeComments':' Please enter approval opinion here (Not required) ,No more than 2000 words.',
                'rejectComments':' Please enter approval opinion here (Not required) ,No more than 2000 words.',
                'remindComments':' Please enter approval opinion here (Not required) ,No more than 2000 words.',
                'remindApproval':' reminds you to approve ',
                'approvalImmediately':' Do it now ',

            },
            //填表单 审批操作按钮等
            "formAction":{
                'submit':' submit ',
                'tempsave':' saveDraft ',
                "copyTo":' Add CC ',
                "addApprover":' Add Approver ',
                "deleteMember":' Click profile photo to delete ',
                "approveSettingByManager":' Approver has been set by administrator ',
                "loadApproveError":' Failed to acquire the approver, click to reload ',
                "addDetailRow":' Add Detail ',
                "pleaseSelect":' Please Select ',
                'agree':' Consent ',
                'attaContributor':' Contributor：',
                'reject':' Reject ',
                'copy':' Add CC ',
                'assignBefore':'Add Approver Ahead',
                'assignAfter':'Add Approver Behind',
                'delete':'delete',
                'edit':' Edit ',
                'resubmit':' Resubmit ',
                'copyForm':' Copy Form ',
                'deleteForm':' Delete Form ',
                'withdrawSubmission':' Withdraw Submission ',
                'reassign':' Reassign ',
                'jumpTo':' Redirect ',
                'convertToEsnTask':' Convert as Task ',
                'withdrawApproval':' Withdraw Approval ',
                'cloudSign':' Cloud Signing ',
                'historySign':' History Sign ',
                'commonPhrase':' Common Phrase ',
                'add':' Add ',
                'new':' New ',
                'continueSubmission':' Continue Submission ',
                "circulate":' Circulate ',
                'read':' Read ',
                'close':' Close ',
                'batchOperation':'Batch Operation',
                'batchConsent':'Batch Consent',
                'selectAll':'All',
                'processMap':'Flow Chart',
                'iformBrowserUrl':'IForm Detail'
            },
            "numberText":{
                'max':' Maximum ',
                'min':' Minimum ',
                'sum':' Sum ',
                'average':' Average ',
                'uppercase':' Amount in Figure ',

            },
            'formTips':{
                "formDetail":' Form ',
                "processDetail":' Process ',
                'documentDetail':' Document ',
                "attachment":' Attachment ',
                "attachmentProcess":' Process Attachment ',
                'uploadFile':' Upload Files ',
                'PleaseUploadFile':' Please Upload Files ',
                "addApproverRepeat":' Cannot repeatedly add approver ',
                "deleteDataTableTips":' Are you sure you wish to delete this detail? ',
                "tempsaving":' Saving ',
                "submitting":' Submitting ',
                "pleaseSelectApprove":' Please select approver ',
                "processErrorManagerFix":' This form has an error in the approval process! Please contact administrator to revise ',
                'branchHasNoProcessor':' No processor for branch. Please select! ',
                'tempsaveSuccess':' Successfully saved ',
                'submitSuccess':' Successfully submit ',
                'operationFailure':' Operation failed! Please try again later ',
                'onLoading':' Loading... ',
                'previewQRcode':' Fail to preview. Do not close QR code during preview. Please try again! ',
                'formatWrongTips':' Format is wrong ',
                'formatErrorTips':' Invalid format ',
                'identifyCodePhone':' Please enter your phone number ',
                "noMoreThan":' No More Than ',
                "noLessThan":' No Less Than ',
                "divisorNotBeZero":' Cannot Be Zero ',
                "required":' is Required ',
                "validText":' Please enter a valid text',
                "textLimit":' Please control within 200 characters ',
                "textAreaLimit":' Please control within 2000 characters',
                "phoneFormatWrong":' The phone number format is wrong ',
                "imageLimitTips":' The phone number format is wrong ',
                "endDataMoreStartDate":' The end date must be greater than the start date, please select again! ',
                "startDataLessEndDate":' Start date must be less than end date, please select again! ',
                "linkFormatTips":' Please enter the correct url format ',
                'moneyLengthLimitTips':' Currently only 16-bit characters are supported ',
                'approvalCommentsTips':' The system automatically fills in the approval comments ',
                'optionOtherSelectPlaceholder':' Please enter other content ',
                'noAttachment':' No Attachment ',
                'noContent':' No Content ',
                'confirmWithdraw':' Are you sure you wish to withdraw the ongoing approval? ',
                'approvalWithDrawing':' Withdrawing approval... ',
                'confirmDeleteForm':' Are you sure you wish to delete current form draft? ',
                'reassignPre':' Are you sure you wish to reassign the approval form to ',
                'reassignLast':' for approving? ',
                'reassignSuccess':' Successfully reassigned ',
                'copyToSuccess':'Successfully CCed ',
                'copyFormSuccess':'Successfully copied form. Jumping now! ',
                'serverRequestError':' Service request failed ',
                'confirmWithdrawApplication':' Are you sure you wish to withdraw this application? ',
                'confirmWithdrawApproval':' Are you sure you wish to withdraw this approval? ',
                'withdrawnSuccess':' Successfully withdrawn ',
                'uploadedSuccess':' Uploaded successfully ',
                'uploadedFailed':' Uploaded failed ',
                'iconMissing':' Lost ',
                'commentsMessage':' Opinion：',
                'finishJumpTo':' Redirect to End ',
                'finishSuccess':' Redirect Success ',
                'finishApprove':' Redirect',
                'prependTaskRecalled':' Add Pre-approver Withdrawn ',
                'appendTaskRecalled':' Add append-approver Withdrawn ',
                'reassignRecalled':' Reassignment Recalled ',
                'jumpedWithNoParticipant':' Skip for No Operator ',
                'processedByOthers':' Processed by Others ',
                'talkWithOtherPre':' Are you sure to chart with ',
                'talkWithOtherAft':' ？',
                'chartWaiting':' waiting...',
                'formEnable':' Form Enable...',
                'formUnEnable':' Form Disable...',
                'sureToDisabledForm':' Are you sure you want to disable this form? ',
                'authorization':' Authorization...',
                'successfullyApproved':' Successfully approved ',
                'successfullyReject':' Successfully reject ',
                'assignParticipants':' Please select an approver to add ',
                'assignTypes':' Please select process adding type ',
                'assignFail':' Failed to add an approver ',
                'assignSuccess':' Successfully added an approver ',
                'designateFail':' Fail to assign ',
                'failToComment':' Fail to comment ',
                'selectRejectStep':' Please select rejecting step ',
                'selectJumpStep':' Please select jumping step ',
                'noJumpStep':' There is no jumping step ',
                'assignInformationEmpty':' Participant in assigning information is required ',
                'branchNoProcessor':' branch no processor. Please select! ',
                'canNotAssign':' task can not to assign ',
                'qrCodeError':' The QR code has expired ',
                'thanksPage':' Thank you for filling in ',
                'delete':' Deleting... ',
                'pleaseEnter':' please enter ',
                'remindSuccess':' Successfully Remind ',
                'Processing':' Processing ',
                'enterRemindingContent':' Please enter reminding content ',
                'structureError':' Template structure error,Please contact the administrator. ',
                'isNotANumber':' is not a numerical type,please modify or re-enter! ',
                'rejectTaskOnlyCompleted':' Rejected task with "Direct approval in rejection step" set can only be completed! ',
                'notLaterThan':' not later than ',
                'notEarlyThan':' not earlier than ',
                'deleteSuccess':' Delete Success ',
                'deleteFail':' Delete Fail, Please try again later ',
                'makeSureDeleteFile':'Are you sure you wish to delete this attachment? ',
                'confirmCC':'Are you sure copy to ',
                'maxStringTips':'Only 16 bit characters are currently supported!',
                'stars':' Star ',
                'batchApprovalMore':'Batch approval only supports the selection of 20 items at most, and only the first 20 items are processed in order when the number of items exceeds 20! Are you sure to Batch approval?',
                'selectApproveItem':"Please select Approval items!",
                'makesureToBatchApproval':' items,Are you sure to Batch approval?',
                'batchSuccess':'Success ',
                'batchFail':', Failure ',
            },
            'time':{
                'year':' Year ',
                'month':' Month ',
                'day':' Day ',
                'hour':' Hours ',
                'min':' Minute ',
                'sec':' Second ',
                'today':' Today ',
                'yesterday':' Yesterday ',
                'thisWeek':' This Week ',
                'lastWeek':' Last Week ',
                'thisMonth':' This Month ',
                'more':' More ',
                'receiveDate':' Receive Date ',
                'finishDate':' Finish Date ',
                'sendDate':' Send Date ',
            },
            'status':{
                'all':' All Status ',
                'over':' Overdue ',
                'normal':' Normal ',
                'finish':' Finished ',
                'going':' In Approval Process ',
                'stop':' Terminated ',
                'inApproval':' In Approval Process ',
                'rejectDraft':' Reject Draft ',
                'draft':' Draft ',
                'submitted':' Submitted ',
                'rejected':' Form Rejected ',
                'rejectedHung':' Task Hung (Reject to Form Creator) ',
                'overdueTerminated':' Overdue Terminated ',
                'overTime':' Overdue ',
                'warning':' Warning ',
                'SubmitApplication':' Submitted an application ',
                'billMaking':' Bill Making',
                'suspendApplication':' To suspend the application '
            },
            'formTypes':{
                'all':' All Types '
            },
            'selectAttachment':{
                'photo':' Taking pictures ',
                'video':' Video ',
                'pic':' Photograph ',
                'files':' Files ',
            },
            'previewExtra':{
                'name':' Attachment.',
                'previewChoose':' Attachment operation selection ',
                'preview':' Preview ',
                'downLoad':' DownLoad ',
                'downLoading':' DownLoading... ',
            },
            'datePicker':{
                'year':' year ',
                'month':' month ',
                'day':' day ',
                'hour':' hours ',
                'min':' minute ',
                'sec':' second ',
                'today':' Today ',
            },
            'dateCalculate':{
                'day':' (Day)',
                'hour':' (Hour)',
                'min':' (Minute)',
                'sec':' (Second)',
            },
            'iconUrl':{
                'refuse':'./imgs/refuse_e.png',
                'agreee':'./imgs/agree_e.png',
            }
        };
    }
    return languageJson;
});